flake8 F811 ./src/cowrie/commands/scp.py
I made sure to delete only the oldest version of the code.

Before
flake8 --count --select=F811 --application-import-names cowrie --max-line-length=120 --statistics .
./src/cowrie/commands/scp.py:209:5: F811 redefinition of unused 'handle_CTRL_D' from line 192
1     F811 redefinition of unused 'handle_CTRL_D' from line 192
1