Cowrie Unit Tests (#188)
* Can run LS in TEST assertion.
Having a problem when assert ends with this:
DirtyReactorAggregateError: Reactor was unclean

* First Test Case Enabled
Modified Example configuration file
Added some test unit cases for all BASE commands
Some more additions to FakeTransport.
Used Official Config file instead of mock config
Separated FakeTransport from unitTests
Added FS commands to testing
Fixed up some problems with grep in test case
You can now run unit tests with trial.
We should probably copy over the data files in a script to a common location....however to run unit tests using trial
trial cowrie/unittests/TestBaseCommands.py
Fixed rmdir test.
Fixed Some Formatting for TwistedChecker